#If running in EKS, AKS, or GKE, 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment_LB
  labels:
    app: spring_LB
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring_LB
  template:
    metadata:
      labels:
        app: spring_LB
    spec:
      containers:
      - name: springboot
        image: vignan91/java_spring:8081
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service_LB
  labels:
    app: spring
spec:
  type: LoadBalancer
  selector:
    app: spring_LB
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8083
